// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GestureHandlerCommon from "./GestureHandlerCommon.bs.js";

var GestureHandlerCallbacks = GestureHandlerCommon.GestureHandlerCallbacks.Make({});

GestureHandlerCommon.Methods({});

export {
  GestureHandlerCallbacks ,
  
}
/* GestureHandlerCallbacks Not a pure module */
