// Generated by ReScript, PLEASE EDIT WITH CARE


var HitSlop = {};

function Make(T) {
  return {};
}

var GestureHandlerCallbacks = {
  Make: Make
};

var GestureType = {};

var GestureRef = {};

function Methods(T) {
  return {};
}

export {
  HitSlop ,
  GestureHandlerCallbacks ,
  GestureType ,
  GestureRef ,
  Methods ,
  
}
/* No side effect */
